### PR TITLE
Add Dockerfile to simplify build

### PR DESCRIPTION
**Pull request by amercer1**
I wanted to share this Dockerfile I created to install Quiver in the [Discovery Environment](http://www.cyverse.org/discovery-environment). If you would like me to make adjustments and or move the file elsewhere, I would be happy to make those changes. 

Building all of the dependencies on a fresh image was a bit of a painful task, and I was hoping to mitigate further trouble for future users. As a result, the Dockerfile may contain lines that are bit overkill but the end result is that the docker image works well.  If you want to take it further, feel free to push to the docker hub for public consumption.

### CODE REVIEW

**Comment by mhsieh** [comment]
Note that trusty/libhdf5-dev (1.8.11) is not compatible with most of the pacbio hdf5 apis since they were developed on hdf5 1.8.12+ .

**Comment by mhsieh** [comment]
You can compare your scripts with mine at
https://github.com/PacificBiosciences/pitchfork/blob/master/.travis.yml
and
https://github.com/PacificBiosciences/pitchfork/blob/master/bin/travisbuild.sh

They probably are doing similar things. :-)

**Comment by amercer1** [comment]
Thanks for the immediate feedback :D If I am able to make the changes to the appropriate versions and such, is this something that your team would want to be pulled in? No hard feelings if not.

**Comment by dalexander** [comment]
There are a lot of ways to build GC, and I will be updating the documents soon to recommend @mhsieh's pitchfork project.

Nonetheless I like the docker approach and I would be willing to merge it if you address @mhsieh's point (use hdf5 1.8.12) and additionally:

- reenable build of ConsensusCore2
- change entrypoint to the more generic "variantCaller" (which is basically a multitool you can use to drive quiver or other algorithms)

I have to warn you that I don't intend to actively maintain the Dockerfile, if it bitrots it's going to get deleted.  So you might want to check in on it periodically.

**Pull request closed without merging**
