### PR TITLE
Remove evil try/catch block that was catching all exception types, sw…

### PR DESCRIPTION
**Pull request by dalexander**
…allowing many serious errors

### CODE REVIEW

**Comment by dalexander** [comment]
@nlhepler please review

**Comment by nlhepler** [comment]
We can't do this. We need to at least catch ABMs that happen during Polish

**Comment by dalexander** [comment]
We'll discuss tomorrow.  I wasn't sure if the C++ code was propagating exceptions.  If the C++ method  returns a bool indicating success, it's arguably bad form to *also* have it throw exceptions.  So my vote would be we rein in the C++ code

**Comment by dalexander** [comment]
Armin's refactor in CC2 is catching the exceptions in C++

Landed this fix with 20b7c79efb80f23f1736098a2499306363b7666b

**Pull request closed without merging**
