### PR TITLE
test for empty bam bug

### PR DESCRIPTION
**Pull request by natechols**
Trying this again.

### CODE REVIEW

**Comment by mdsmith** [comment]
Failed due to an unexpected warning in the cram test (x2):

[WARNING] /home/ubuntu/GenomicConsensus/tests/data/sanity/empty.subreads.bam contains no reads!

Should I turn this down to an INFO in pbcore, or do we want the warning?

**Comment by dalexander** [comment]
where is that warning coming from?

**Comment by mdsmith** [comment]
That is coming from the DataSet API when the files are opened.

**Comment by natechols** [comment]
I think we want the warnings.  I'll add them.

**Comment by natechols** [comment]
@dalexander this is passing now, can we merge?

**Comment by dalexander** [comment]
I have other plans for this.  I want to fix the root problem in the pbi reader.  Martin's fix at the dataset layer was just a workaround, from my perspective.  So let's keep this open as a reminder to me.

**Comment by natechols** [comment]
Could we instead create a failing test for pbcore (I can do this now) and check in my cram test?  I'm really not comfortable calling the original bug fixed without automated testing.

**Comment by dalexander** [comment]
OK.

**Pull request merged**
