### PR TITLE
added failing test

### PR DESCRIPTION
**Pull request by natechols**
For sane behavior when an otherwise valid AlignmentSet contains an empty BAM file.  Current result:

    $ cram tests/cram/bad_input.t
    !
    --- bad_input.t
    +++ bad_input.t.err
    @@ -7,3 +7,22 @@
       $ DATA=$TESTDIR/../data/sanity
       $ REF=/pbi/dept/secondary/siv/references/lambdaNEB/sequence/lambdaNEB.fasta
       $ variantCaller --reference $REF -o contig.fasta $DATA/mixed.alignmentset.xml
    +  [WARNING] /home/nechols/src/GenomicConsensus/tests/data/sanity/empty.subreads.bam contains no reads!
    +  [WARNING] /home/nechols/src/GenomicConsensus/tests/data/sanity/empty.subreads.bam contains no reads!
    +  [ERROR] Traceback (most recent call last):
    +    File "/home/nechols/py/local/lib/python2.7/site-packages/GenomicConsensus-2.0.0-py2.7.egg/GenomicConsensus/main.py", line 332, in main
    +      self._mainLoop()
    +    File "/home/nechols/py/local/lib/python2.7/site-packages/GenomicConsensus-2.0.0-py2.7.egg/GenomicConsensus/main.py", line 219, in _mainLoop
    +      for chunk in chunks:
    +    File "/home/nechols/py/local/lib/python2.7/site-packages/GenomicConsensus-2.0.0-py2.7.egg/GenomicConsensus/reference.py", line 229, in fancyEnumerateChunks
    +      rows = reader.readsInRange(refId, 0, refLen, justIndices=True)
    +    File "/home/nechols/py/local/lib/python2.7/site-packages/pbcore-1.2.8pre-py2.7.egg/pbcore/io/align/BamIO.py", line 389, in readsInRange
    +      ix = self.pbi.rangeQuery(winId, winStart, winEnd)
    +    File "/home/nechols/py/local/lib/python2.7/site-packages/pbcore-1.2.8pre-py2.7.egg/pbcore/io/align/PacBioBamIndex.py", line 207, in rangeQuery
    +      (self.tStart  < winEnd) &
    +    File "/home/nechols/py/local/lib/python2.7/site-packages/pbcore-1.2.8pre-py2.7.egg/pbcore/io/align/PacBioBamIndex.py", line 172, in __getattr__
    +      raise AttributeError, "pbi has no column named '%s'" % columnName
    +  AttributeError: pbi has no column named 'tId'
    +
    +  [ERROR] Aborting
    +  [255]

    # Ran 1 tests, 0 skipped, 1 failed.

### CODE REVIEW

**Comment by natechols** [comment]
@dalexander just queuing this up for later

**Comment by natechols** [comment]
The current test failure is due to the original pbcore bug - mdsmith has fixed this so I assume CircleCI is still using an obsolete version.

**Comment by dalexander** [comment]
not fixed yet, I need to fix it.

**Comment by natechols** [comment]
Bah, this is now out of date.  Will try again.

**Pull request closed without merging**
