### PR TITLE
add consensus.fasta to output in variantCaller TC

### PR DESCRIPTION
**Pull request by ben-lerch**
this is to address SL-428.

### CODE REVIEW

**Comment by natechols** [comment]
This is the wrong repository, and that's just going to break anyway, since it's missing the connection that tells variantCaller to output the appropriate file name.

**Comment by ben-lerch** [comment]
what is the right repository? variantCaller is already outputting a file called "consensus.fasta" So I think we just need to have the TC recognize that. correct me if I'm wrong.

**Comment by natechols** [comment]
This repository lives in BitBucket now.  And the fact that the tool contract agrees with the output file right now does not guarantee that this will continue to work, since the underlying name could change.  You need to write this so that whatever file name is specified in the tool contract is what variantCaller uses.

**Comment by ben-lerch** [comment]
how does this look?
http://bitbucket.nanofluidics.com:7990/projects/SAT/repos/genomicconsensus/pull-requests/15/diff

**Pull request closed without merging**
