### PR TITLE
loop optimization

### PR DESCRIPTION
**Pull request by natechols**
Getting rid of an unnecessary all-vs-all loop - not a complete solution for scaling issues (large contigs will probably still be bottlenecks) but it fixes our immediate use case.

### CODE REVIEW

**Comment by natechols** [comment]
PS. The cram test modification is superfluous but harmless - I was playing around with more verbose logging (but left it off for now).

**Comment by natechols** [comment]
@dalexander is this okay?  I got rid of the output redirect that was there originally

**Comment by dalexander** [comment]
let me review.... hold on

**Comment by natechols** [comment]
Okay, here is a more efficient implementation.  It takes about the same amount of time running the original use case of many short contigs, but it's at least 4x faster than my previous attempt when using a single chromosome with 20000 regions, and certainly orders of magnitude faster than the version before that.

**Comment by dalexander** [comment]
Wow, awesome!  Nice work Nat, I wasn't expecting you to take this any further!  

This looks terrific, the only thing I worry about is edge/boundary conditions.  Do any of the tests have variants exactly on region boundaries?  Would be good to check those.

**Comment by natechols** [comment]
I'll add a Python unit test - would be good to get some CircleCI coverage for this anyway.

**Comment by natechols** [comment]
For the sake of completeness, two other observations:

- If the input GFFs are both in sorted order we could make this linear - the sorting overhead may be considerable however.  (The chunking doesn't preserve order, although the individual chunks are themselves in sorted order.)

- I tried to derive the region index automatically (which would also be linear) but it turns out that the region sizes are inconsistent - in at least one case the final region of a contig was longer than the preceeding regions.  This is probably worth looking into in the future.

**Pull request merged**
