### PR TITLE
test arrow support in tool contract mode

### PR DESCRIPTION
**Pull request by natechols**

### CODE REVIEW

**Comment by natechols** [comment]
I don't understand why this is breaking - is the CircleCI build using an incompatible version of ConsensusCore?

**Comment by dalexander** [comment]
did we ever resolve this? or is this no longer needed

**Comment by natechols** [comment]
I don't think we have any command-line tests that use arrow; it would be nice to have for ensuring that ConsensusCore2 is being built properly.

**Comment by dalexander** [comment]
Let's roll the dice

**Pull request merged**
