### PR TITLE
Accurate siteCoverage (account for filtering)

### PR DESCRIPTION
**Pull request by nlhepler**

### CODE REVIEW

**Comment by dalexander** [comment]
Thanks Lance, a couple comments...  Overall I really like the idea and it could be very useful for diagnostic purposes.  However a couple concerns:

1. I don't want to just redefine "coverage"---it's something that has had a fixed meaning for some time, and also the present fix as proposed would cause it to have a different meaning depending on the algorithm (quiver, plurality, poa, arrow).  Better would be to add a new concept... "postFilteringCoverage", which could make its way into the variants.gff.  We would have to amend the spec as well: https://github.com/PacificBiosciences/GenomicConsensus/blob/master/doc/VariantsGffSpecification.rst

2. This changes the return type of `consensusFromAlignments` from an object cssObj to a tuple (cssObj, siteCoverage).  I believe (?) you did this because you didn't want to put the siteCoverage (which is a vector over reference coordinates, no?) as a new field in the ArrowConsensus class, which mostly reflects consensus information in _consensus_ coordinates.  However I would actually prefer that we put this information in the ArrowConsensus class (suitably named and documented, to indicate that this field is in reference coords) and keep the return type to be a cssObj.  Believe it or not, this function is also called from `dumbview` and I'd rather we don't break it.

**Comment by nlhepler** [comment]
@dalexander can we make a story for this and I can refactor it into another attribute called effectiveCov or somesuch? (actually ideas for varname would be helpful)

**Comment by dalexander** [comment]
Good idea.  I'll open a story.

**Comment by nlhepler** [comment]
@dalexander on the topic of new features for variantCaller, perhaps a context attribute as well? surrounding 5bp radius window or symmetric end of homopolymer?

**Comment by dalexander** [comment]
fixed already

**Pull request closed without merging**
